### ISSUE TITLE
GRID outage icon not shown when outage in progress[BUG]

### ISSUE THREAD

**Issue by BugsBunnyRSA** [flixlix/power-flow-card-plus#250] opened 2023-06-02 06:34 UTC
**Describe the bug**
Selecting an entity that shows POWER OUTAGE status and selecting an icon does not change the default GRID icon when an outage occurs. The main GRID icon remains unchanged. A few versions back the POWER OUTAGE icon replaced the main icon if an outage was in progress. 

**To Reproduce**
1. Go to Power Flow Card EDIT
2. Click on HOME
3. Scroll down to POWER OUTAGE
4. Select ENTITY and ICON and edit STATE of ALERT.
5. Save.
6. GRID icon remains the default even if POWER OUTAGE is triggered.

**Expected behavior**
The GRID icon should change to the icon selected for POWER OUTAGE. The ALERT label changes, but not the icon

**Screenshots**
GRID icon should change when a POWER OUTAGE occurs

![image](https://github.com/flixlix/power-flow-card-plus/assets/127091127/3c549322-700f-4c6c-9c56-586e906059ee)

**Desktop (please complete the following information):**
 - OS: [Windows 10 + Android App]
 - Browser [Chrome]

**Smartphone (please complete the following information):**
 - Version [Chrome V113.0.5672.127, HomeAssistant V2023.3.0-full]

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment] 2023-06-02 06:35
Duplicate of #247 
Will be available in the next version

**Closed by flixlix** 2023-06-02 06:35 UTC
Labels: bug

**Comment by BugsBunnyRSA** [comment] 2023-06-02 06:47
Thanks.
