### ISSUE TITLE
feature request: multiple additional items, including additional solar production

### ISSUE THREAD

**Issue by umrath** [flixlix/power-flow-card-plus#54] opened 2023-04-11 09:24 UTC
This card is providing what was missing in power-flow-card: individual additional items

It would be great to be able to define more than 2 individual items and also be able to define more than 1 solar device for production.

**Comment by flixlix** [comment] 2023-04-11 13:13
Where would you suggest that the additional individual devices be displayed? I think 2 individual devices is more than enough for most people... But I'm open to suggestions

**Comment by flixlix** [comment] 2023-04-11 13:35
Multiple solar sources is already something that is not planned, since I don't know how it would be displayed and handled in the card combined with multiple directions to go to. That issue was already closed and marked as not planned [#23](https://github.com/flixlix/power-flow-card-plus/issues/23)

**Comment by umrath** [comment] 2023-04-11 14:55
Another alternative:
"individual2" can hold multiple entities, sums them up (and displays the sum) but also displays the entity with the currently highest consumption. That would require no additional real estate and still provide more information and support for more entities.

**Comment by flixlix** [comment] 2023-04-11 15:09
Feel free to create a PR, but currently I feel this falls outside of the scope of this card. Plus, I am already very occupied with other advanced features, so I don't think I could give this feature the time and attention it needs... I hope you can comprehend

**Closed** 2023-04-11 15:09 UTC
Labels: enhancement

**Comment by umrath** [comment] 2023-04-11 15:10
That's fine.
I just wanted to place the idea, in case someone has spare time and interested to follow up on it.

**Comment by flixlix** [comment] 2023-04-11 15:17
Ok, since the issue is closed, the probability that anyone will see it is very low, so I'll add a todo-list to the readme and encourage people to contribute to the project 😊

**Comment by toluen-kodekrets** [comment] 2023-04-26 18:42
Since I started using your card I fell in love imidatly, its in many dashboards, and featured in my wall tablets. I wanten to add this myself to feature request. I have one for electric car charger also one for my water heater. Additional I want to add combined sensor for all my underfloor heating, and other powerhungry apliance, so I can at a glance see what is using power, as I want to stay under 5KW usage du to cheaper utilitys.

One suggestion for how to view mutible bubble is the follwing: Im using the "display_zero: false" feature, so the bubble dissapears when it is off. If we have mutliple individuals, it wont be so cluttered. Its not often you have everything on at once.

**Comment by TheodorKleynhans** [comment] 2023-05-24 09:00
A minor variation of this would be to allow multiple individual items to be configured, but only ever show the 2 with the highest usage.

**Comment by blubbel42** [comment] 2023-05-30 12:11
The thing with the list sounds very nice- at the moment I'm doing this with a auto-entities card.

**Comment by Neuvidor** [comment] 2023-09-17 10:22
> A minor variation of this would be to allow multiple individual items to be configured, but only ever show the 2 with the highest usage.

I think it Would be a very Nice work around solution.
I have for example my Heating, my hot water, my kitchen and the TV.

**Comment by Hadatko** [comment] 2023-09-30 06:30
Not sure why is this ticket closed when it is something everybody feels they want :D Even when author feels he doesn't have time for that it can stay opened  ;) 

So: 
+1

**Comment by marcuccie** [comment] 2023-09-30 11:01
I'd like to add multiple items too.

grid power in
solar power
solar power returned to grid (substract solar power - home total power when home total power <= solar power)
home total power
home followed items (boiler, kitchen, washing machines, heaters etc)
home "other" (susbstract home total power - followed items)

**Comment by giuian69** [comment] 2023-10-08 09:21
Maybe the individual items can be slightly smaller and four? If the problem is the space in the card. In many domotic house are more than two power meter... For example i have one for the dishwasher, one for the washing machine, one for the oven and one for the air conditioning.
Please you consider, if is possible,  to reopen this feature request.

**Comment by edlestau** [comment] 2023-11-07 13:11
Another example would be different areas in the house where consumers are present
- heat pump
- garden
- kitchen
- Electric car
etc
It would be great to be able to display these in different additional items.
I think the idea of dynamically expanding the view to the right on mouse-over is smart.

**Comment by redstyle82** [comment] 2023-11-29 12:47
Any news on that?

**Comment by umrath** [comment] 2023-11-29 12:58
It's closed.
The author has clearly stated that he is not interested in this feature. So, unless someone forks it and creates it, presumably nothing will ever happen.

**Comment by d3z1b3l** [comment] 2024-02-04 12:27
@flixlix 
Hi, i have a "maybe :-)" easy solution:
Is it possible to build one separate card, which is only a circle with all functions of an individual device?

For me it would be ok. 
I know, your very nice lines will not be available and we can not see the flow, but so everybody can have a nice overview in same style about all consumers.

For me it would be great, because I have electric car, and different buildings with smart meters :-)
It can be a good overview!


I'm not so good in programming, but if it would be not so much work, maybe a lot copy/paste, it would be great if you will do!? ;-)

greets, d3z1b3l

**Comment by flixlix** [comment] 2024-02-04 12:32
@umrath 
I was able to implement up to 4 individual devices in the new beta! Hopefully this is what you had in mind 😊

**Comment by d3z1b3l** [comment] 2024-02-04 13:05
@flixlix 
Wow 🤩 very nice! 👍🏻 
Thanks!!

4 is much better!!!
Is 6 maybe possible for next Version? 😀😉

greets, d3z1b3l

**Comment by umrath** [comment] 2024-02-04 17:37
This looks really good and is pretty much exactly what I had in mind.
I'm super happy!

**Comment by TheodorKleynhans** [comment] 2024-02-04 17:42
> @umrath I was able to implement up to 4 individual devices in the new beta! Hopefully this is what you had in mind 😊

This is awesome! Thanks for putting in the effort to make this change.

Now that the editor allows adding multiple devices, it will be great if it allows you to add many devices and then have a setting to only show the top 2/4/...

**Comment by marcuccie** [comment] 2024-02-04 20:25
Great!

Thanks a lot

![image](https://github.com/flixlix/power-flow-card-plus/assets/124093154/5fa478eb-3bbc-4bda-91da-279a51f56957)

**Comment by giuian69** [comment] 2024-02-04 20:51
Many thanks!!

**Comment by Lova1987** [comment] 2024-02-06 14:36
hello, i saw that i can't see new  multiple devices from phone and tablet ... can you confirm?

**Comment by Lova1987** [comment] 2024-02-06 16:07
hello everybody... if i use 
![image](https://github.com/flixlix/power-flow-card-plus/assets/158744739/186cc3bc-dc54-4d44-9466-f718865b6cff)
and i add       display_zero_tolerance: "xxx" to remove the little consumption of the induction stove the individual devices disappears      :-(... 
from
![image](https://github.com/flixlix/power-flow-card-plus/assets/158744739/806a6f5b-5482-4015-a69c-5b457419a6d0)
to
![image](https://github.com/flixlix/power-flow-card-plus/assets/158744739/416b44f9-f98d-46b4-ad52-7ba4b8dcc03f)
 can i solve it? i wuant only to remove the line when te device is in stanby( < 20w) THANKS

**Comment by Thomansky** [comment] 2024-04-17 08:31
It would be nice if that were possible



![IMG_2328](https://github.com/flixlix/power-flow-card-plus/assets/73141171/c4cec658-f161-487a-a918-3a6379e04934)

**Comment by Arise** [comment] 2024-05-29 17:00
I know I'm a spoiled kid, but it seems I need 6 individual entities. :)

I'm on a triphase system, each level has 1 phase, 1 electric car, 1 boiler heater and 2 air conditioners on level1.

So I would like to see the house consumption on each phase (which tells me the consumption on each level), then I need to know the car charger, the boiler and the total AC consumption, and that brings me to 6 individual entities. :)

**Comment by HaareistNase** [comment] 2024-06-06 09:47
Dear Sirs,
is there a possibility to add more individual entities.
There must be no option to dispay more, but a option to define more. That would be nice.
Maybe a posibility to define 8 or 10 individual entities, and only the active are displayed like how it works actually.
I love that the individual entities appear and dissapear e.g. when I charge the car the bubble shows up, and when I stop charging the bubble dissapears.
You did awesome on this. Thank you very much.

**Comment by Thomansky** [comment] 2024-06-06 09:56
It would be nice to add more production and more selling identities.

**Comment by borodaaaaa** [comment] 2024-06-29 05:10
It would be nice to be able to add more than 4 individuals and show only top 4… or may be only top 2  if prefer minimalistic  design

**Comment by Johnnyd1965** [comment] 2024-07-25 22:55
If you put an entity into the Secondary info in each item you will be able to include a total of 8 individual items.

**Comment by HaareistNase** [comment] 2024-07-26 15:55
> If you put an entity into the Secondary info in each item you will be able to include a total of 8 individual items.

But they show only up, if the first entity is displayed. So the have to "fit" somehow.

**Comment by borodaaaaa** [comment] 2024-07-26 20:21
The secondary is more for total consumption today On 27 Jul 2024, at 01:55, HaareistNase ***@***.***> wrote:﻿

If you put an entity into the Secondary info in each item you will be able to include a total of 8 individual items.

But they show only up, if the first entity is displayed. So the have to "fit" somehow.

**Comment by Exilim77** [comment] 2025-07-08 12:44
Hello, are you still working on more than 4 individuals? 

The Posting from borodaaaaa on Jun 29, 2024 is a good suggestion 👍
