### ISSUE TITLE
[BUG] Bubble are misaligned.

### ISSUE THREAD

**Issue by EkielZan** [flixlix/power-flow-card-plus#465] opened 2024-01-15 13:47 UTC
**Describe the bug**
Hi,
I've tried to use the new version of the card and it seems that when adding individual consumer something is broken.

![image](https://github.com/flixlix/power-flow-card-plus/assets/7491931/11cfb345-6ac3-475f-ba38-004e60069fe5)

I used to have 2 individuals consumer and it use to work but with the new version, it doesn't anymore as shown in the image here above.

here is my yaml configuration : 
`
type: custom:power-flow-card-plus
entities:
  fossil_fuel_percentage:
    entity: sensor.co2_signal_pourcentage_d_energies_fossiles_du_reseau
    state_type: percentage
    display_zero: true
  grid:
    entity: sensor.p1_meter_active_power
    display_zero_state: false
    display_zero: false
    color_circle: true
  solar:
    entity: sensor.solaredge_current_power
    display_zero_state: true
  home: {}
  individual:
    - entity: sensor.kpme_1_power
      display_zero_state: true
      display_zero: true
      icon: mdi:washing-machine
      color: '#ff8870'
      name: Séchoir
      color_icon: false
    - entity: sensor.shelly1_power
      display_zero_state: true
      display_zero: true
      icon: mdi:washing-machine
      color: '#ffb880'
      name: Lavage
      color_icon: false
    - entity: sensor.plusplugs_switch_0_power
      display_zero_state: true
      display_zero: true
      icon: mdi:radiator
      color: '#ffb880'
      name: Chauffage
      color_icon: false
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000

`

**Comment by manu33xtro** [comment] 2024-01-18 09:54
Hi,
First, thanks for very good job, amazing card !
I have the same issue with my card :
![image](https://github.com/flixlix/power-flow-card-plus/assets/3975794/a38d79f2-a582-4526-ac6e-a052be1a68f7)

My code :
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.meter_1_active_power
    color_value: true
    invert_state: true
    color_icon: true
    color_circle: true
    use_metadata: true
    icon: mdi:transmission-tower
    name: 'Réseau '
  solar:
    entity: sensor.onduleur_maison_active_power
    display_zero_state: false
    icon: mdi:solar-power-variant
    color_icon: true
    color_value: true
    secondary_info:
      entity: sensor.onduleur_maison_inverter_internal_temperature
      unit_of_measurement: °c
      decimals: 1
      color_value: true
      unit_white_space: true
      display_zero: true
  home:
    entity: sensor.meter_1_active_power
    color_value: true
    color_icon: true
    subtract_individual: true
    override_state: false
    secondary_info:
      entity: sensor.inversion_val_factor
      unit_of_measurement: '%'
      decimals: 1
      color_value: true
      unit_white_space: true
    name: Maison
  fossil_fuel_percentage: {}
  individual:
    - entity: sensor.wallbox_portal_charging_power
      name: Wallbox
      color_icon: true
      color_value: true
      secondary_info:
        template: ''
        entity: sensor.ge255kr_battery_level
        unit_of_measurement: '%'
        color_value: true
      icon: mdi:car-electric-outline
      display_zero: true
    - entity: sensor.prise_salon_puissance
      color_icon: true
      color_value: true
      icon: mdi:television
      name: home cinéma
      display_zero_state: true
      calculate_flow_rate: true
      show_direction: true
      inverted_animation: false
      secondary_info:
        entity: sensor.prise_salon_courant
        color_value: true
        display_zero: false
        unit_of_measurement: A
        decimals: 1
      display_zero: true
      display_zero_tolerance: 30
    - entity: sensor.sonoff_10012d9445_power
      color_icon: true
      color_value: true
      icon: mdi:fish
      name: Bassin
      display_zero_state: true
      calculate_flow_rate: false
      show_direction: true
      inverted_animation: false
      secondary_info:
        entity: sensor.sonoff_10012d9445_current
        color_value: true
        display_zero: true
        unit_of_measurement: A
        decimals: 1
    - entity: sensor.prise_3_puissance
      name: Machines
      color_value: true
      color_icon: true
      calculate_flow_rate: true
      icon: mdi:washing-machine
      secondary_info:
        entity: sensor.prise_3_courant
        color_value: true
        decimals: 1
        unit_of_measurement: A
clickable_entities: true
display_zero_lines:
  mode: transparency
  transparency: 5
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 10000
transparency_zero_lines: 0

**Comment by flixlix** [comment] 2024-01-18 11:53
Duplicate of https://github.com/flixlix/power-flow-card-plus/issues/462
already fixed, will be available in the next version

**Closed by flixlix** 2024-01-18 11:53 UTC
Labels: bug
