### ISSUE TITLE
[BUG] Card always in front

### ISSUE THREAD

**Issue by DMedina559** [flixlix/power-flow-card-plus#438] opened 2023-12-06 16:32 UTC
**Describe the bug**
When using a popup card the underlying energy or power flow card will always show on top

**To Reproduce**
1. Set up a pop up card from HACS on a dashboard with the Energy Flow Card
2. Open the Pop Up

**Expected behavior**
The underlying card shouldn't show on top

**Screenshots**
Issue:
![Screenshot_20231206_072854_Home Assistant](https://github.com/flixlix/power-flow-card-plus/assets/68480549/c0ecc1c9-83be-4d65-b6c1-dfeb82b30525)

Expected:
![Screenshot_20231206_082904_Home Assistant](https://github.com/flixlix/power-flow-card-plus/assets/68480549/a9034de8-80d5-45cd-a90c-605a8882fcee)

Temporary fix for now is to use card mod:

```
type: custom:mod-card
style: |
  ha-card {
    z-index: 0;
  }
card:
  type: custom:energy-flow-card-plus
```

**Comment by flixlix** [comment] 2023-12-06 18:10
Duplicate of:
https://github.com/flixlix/power-flow-card-plus/issues/406

**Closed by flixlix** 2023-12-06 18:10 UTC
Labels: bug
