### ISSUE TITLE
[BUG] Card not working in mobile app when Individual1 and/or Individual 2 is added

### ISSUE THREAD

**Issue by PSXDupe** [flixlix/power-flow-card-plus#598] opened 2024-04-22 08:34 UTC
**Describe the bug**
Card works correctly on the mobile app, until you add Individual1 or Individual2, then is breaks, "You are using an outdated......"

**To Reproduce**
1. Create a card
2. Setup grid, home, solar (if needed)
3. Save
4. View on Mobile App, working correctly
5. Add Individual1 to the card
6. View on Mobile App, card will be giving error

**Expected behavior**
Should display Individual1 and/or individal2

**Screenshots**

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung A52
 - OS: Android 14
 - Browser Mobile App
 - Version 0.22

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [ ] I have the latest version of the card installed.

- [ ] I have cleared my browser cache **after** installing, updating and configuring the card.

- [ ] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment] 2024-04-22 08:39
duplicate of #569, #572, #574.

Please use the new configuration with `individual` instead of `individual1`, `individual2`, etc...

**Closed by flixlix** 2024-04-22 08:39 UTC
Labels: bug

**Comment by PSXDupe** [comment] 2024-04-22 08:45
I was using the GUI to create it, the GUI creates Individual1 and Individual2

**Comment by PSXDupe** [comment] 2024-04-22 08:47
Seem the browser cache was the issue, appologies.

**Comment by flixlix** [comment] 2024-04-22 08:47
That probably means then that your pc is holding on to the old version, can you try [clearing your cache](https://how-can-i.luca-felix.com/clear-cache)?
