### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jodewee** [flixlix/power-flow-card-plus#160] opened 2023-05-08 12:13 UTC
**Describe the bug**
UI not working
**To Reproduce**
add card 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40162805/236820882-10396f0a-73fc-438a-94cc-ec1557d10ac7.png)

**Additional context**
Visual editor is not supported for this configuration:
s.entries is not a function

**Comment by flixlix** [comment] 2023-05-08 12:15
Duplicate of #158

**Closed by flixlix** 2023-05-08 12:15 UTC
Labels: bug

**Comment by flixlix** [comment] 2023-05-21 17:43
I created a fork of Card Mod with the changes from my PR. Feel free to install that version and give feedback on wether or not it works :)

https://github.com/flixlix/lovelace-card-mod/
