### ISSUE TITLE
[BUG] Secondary Info doesn't show negative values

### ISSUE THREAD

**Issue by pacemaker82** [flixlix/power-flow-card-plus#521] opened 2024-03-18 12:07 UTC
**Describe the bug**

When the value of the secondary info entity is a negative, the secondary info label shows `0`

**To Reproduce**

Setup a secondary info (https://github.com/flixlix/power-flow-card-plus#secondary-info-configuration)

Entity can be both positive or negative (in this case it is showing the currency value per kWh imported/exported)

```
        secondary_info:
          entity: sensor.realtime_income
          unit_of_measurement: £/hr
          decimals: 2
          unit_white_space: true
```

**Expected behavior**
Both positive and negative values should appear

**Screenshots**
![IMG_0764](https://github.com/flixlix/power-flow-card-plus/assets/157808562/8589ecd8-d776-47da-96c9-db37b5aa9aa0)

Not a great example as the import is very low, but its same for whatever the import value is, the secondary **negative** value shows as `0`

Here is an example of it working with a **positive** value:

<img width="276" alt="Screenshot 2024-03-18 at 12 12 23" src="https://github.com/flixlix/power-flow-card-plus/assets/157808562/94c485fa-d9f0-4d6e-9632-e617537a5ebf">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 122

**Additional context**
<img width="551" alt="Screenshot 2024-03-18 at 12 10 12" src="https://github.com/flixlix/power-flow-card-plus/assets/157808562/4427b38b-de74-4448-8277-715410270a21">

This is showing the referenced entity and how the value can be +/-

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment] 2024-03-26 10:37
Duplicate of #466.
I'll try to release the next version soon

**Closed by flixlix** 2024-03-26 10:37 UTC
Labels: bug
