### ISSUE TITLE
[BUG] UI editor not working with 0.1.1

### ISSUE THREAD

**Issue by tubalainen** [flixlix/power-flow-card-plus#166] opened 2023-05-09 15:17 UTC
**Describe the bug**
An error shows up when trying to add the custom card to the Dashboard.

**To Reproduce**
Edit Dashboard -> Add Card -> Scroll down to Custom Flow Card Plus -> Click

**Expected behavior**
The UI editor will work?

**Screenshots**
![image](https://github.com/flixlix/power-flow-card-plus/assets/26795429/77b5b703-0901-4ec2-8c30-aa127d533fb3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome (Tried Edge as well, tried incognito - same issue)
 - Version: Latest

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment] 2023-05-09 15:18
Duplicate of #160 #158

**Closed by flixlix** 2023-05-09 15:18 UTC
Labels: bug

**Comment by flixlix** [comment] 2023-05-21 17:43
I created a fork of Card Mod with the changes from my PR. Feel free to install that version and give feedback on wether or not it works :)

https://github.com/flixlix/lovelace-card-mod/
