### ISSUE TITLE
 Cosmetic operation CSS Style

### ISSUE THREAD

**Issue by whyisthisbroken** [flixlix/power-flow-card-plus#224] opened 2023-05-30 04:14 UTC
**Describe the bug**
Not a Bug, its a cosmetic problem.

**Expected behavior**
Looks nice, i mean - it looks nice but could be better :)
I tryd to modify my Browser Zoomlvl etc, i think its a css styling problem.

**Screenshots**
![Screenshot 2023-05-30 060907](https://github.com/flixlix/power-flow-card-plus/assets/96284773/0f5a578d-c1cc-49f5-9ec4-ba5a819b45b9)

- [X ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment] 2023-05-30 05:31
Yeah the main difficulty here is making the lines work in every scenario.
I adjusted the lines for a scenario where you have a battery and solar panels:
![Battery and Solar](https://github.com/flixlix/power-flow-card-plus/assets/61006057/6b5a2b24-8ab8-4b35-b7a6-fed203596123)
The problem is that when you remove the battery, the lines move somewhat down to keep themselves centered in relation to home and grid.
Another issue is the fact that this card also has to be somewhat responsive. The most common use case is putting it in the sidebar, there it has a lot less space to work with:
![Battery and Solar - Sidebar](https://github.com/flixlix/power-flow-card-plus/assets/61006057/3bc82703-7916-4277-be9d-1d54ae59ffa8)
As you can see, it's not perfect.

I'll try my best to align the lines better 😗

**Comment by flixlix** [comment] 2023-06-01 09:23
Should be fixed in #244 
Available in the next version 🥳

**Closed by flixlix** 2023-06-01 09:23 UTC
Labels: bug
