### ISSUE TITLE
Alternative of Grid Import

### ISSUE THREAD

**Issue by gordio** [flixlix/power-flow-card-plus#286] opened 2023-06-16 03:28 UTC
In Ukraine, from time to time we must run fuel generator. So i'm interesting in adding "grid backup (second source)"

So it will be nice to add second power source under Grid Import icon, with possibility to define alternatives. Like:
1. Generator (Ecoflow Dual Fuel, that can be started automatically on low battery);
2. Car V2G as backup source;
3. Connected external Invertor

P.S. I'm trying to cover all possible cases, thats why thinking on some list of backup sources.

**Comment by gajotnt** [comment] 2023-06-16 13:52
![Captura de ecrã 2023-06-16 135147](https://github.com/flixlix/power-flow-card-plus/assets/25504364/16c0df06-4060-4934-af77-e54bcb032c18)

**Comment by flixlix** [comment] 2023-06-19 14:10
As @gajotnt posted, it is possible to define a power outage scenario, but I think you're looking for something that displays the values in case of an outage.

A few releases ago I added the functionality for bidirectional individual devices, in which a positive value goes from home to it and a negative value goes from it to home (by default at least)

**Comment by gordio** [comment] 2023-06-19 17:14
Let me show you example:
![power_card_plus_proposition](https://github.com/flixlix/power-flow-card-plus/assets/141126/9fe2243c-2158-4da4-bc57-ca962cc4563e)

**Comment by NemesisXB** [comment] 2023-06-20 07:32
+1 for this.

Also agree that the line should not go to the battery, the generator can charge the battery and/or supply the home loads.
Maybe something like this.
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/660a2d19-5c35-4b37-af1d-708d65b25637)

If you do not select a secondary AC input source, then it looks like it currently does, but as soon as you select a secondary AC input source the Mains node is added. The mains node can be auto calculated based on the other values flowing in and out. Also with an Off state (like the grid Power Outage), to show whether the generator is running or not.

**Comment by flixlix** [comment] 2023-06-20 20:21
This is a duplicate of #110.
It needs some more thought to where it flows

**Comment by iJAY86** [comment] 2023-07-10 08:41
Something like this maybe. ![IMG_20230710_094007.jpg](https://github.com/flixlix/power-flow-card-plus/assets/23543483/c1bf7fe4-dccb-43bc-83e5-87fdd70304de)

**Comment by iJAY86** [comment] 2023-07-10 08:44
Or if possible, maybe the ability to use template for icon change depending on power source.

**Closed** 2023-07-25 12:12 UTC
Labels: enhancement

**Comment by flixlix** [comment] 2023-07-25 12:22
Added in version [0.1.7](https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1.7)! 🥳

I decided to have the generator be inside the grid circle and as such, replacing the grid entity once it fails
