### ISSUE TITLE
[BUG] Individual Entities not displayed on Android Mobile App

### ISSUE THREAD

**Issue by stujonesuk** [flixlix/power-flow-card-plus#616] opened 2024-04-28 13:23 UTC
**Describe the bug**
Individual Entities are not displayed when using the Home Assistant Android Mobile App

**To Reproduce**
1. Configure card with grid, solar, home, and two individual entities
2. View card in browser, and also in mobile app

**Expected behavior**
All configured entities should be displayed.

**Screenshots**
Card as viewed in browser, displaying all configured entities:
![image](https://github.com/flixlix/power-flow-card-plus/assets/47328516/3129755d-6fd8-49b8-962e-f7f37e1be7e2)

Card as viewed in Android HomeAssistant app, missing Hot Water and Car entities:
![image](https://github.com/flixlix/power-flow-card-plus/assets/47328516/6216b011-0dfb-4472-a6a4-811a36a0ac6e)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 14, OneUI 6.0
 - HASS App Version: 6th April 2024 update

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment] 2024-04-28 13:37
duplicate of #505

**Closed by flixlix** 2024-04-28 13:37 UTC
Labels: bug
