### ISSUE TITLE
s.entries is not a function [BUG]

### ISSUE THREAD

**Issue by beppexx80** [flixlix/power-flow-card-plus#271] opened 2023-06-08 07:40 UTC
**Describe the bug**
s.entries is not a function

**To Reproduce**
1. Go to 'Edit Card'
3. Scroll down

**Screenshots**
![Immagine 2023-06-08 093506](https://github.com/flixlix/power-flow-card-plus/assets/24457253/71ba55eb-baa9-4029-9ae1-d50e93856656)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Version 114.0.5735.110 (Build ufficiale) (a 64 bit)

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment] 2023-06-08 07:46
Known issue.
From the README:

> ⚠️ Version 0.1 introduced the UI Editor. This Editor is currently incompatible with Card Mod. I created a PR to fix this issue, but it hasn't been merged yet. Here is the [PR #277](https://github.com/thomasloven/lovelace-card-mod/pull/277). Since it hasn't been merged yet, I also released a fork with the changes from the PR. Installing this Version of Card Mod you can use this card in conjunction with Card Mod. [Here is my fork](https://github.com/flixlix/lovelace-card-mod)

Duplicate of #251, #207, #219, #166, #160, #158, #133 and probably more...

**Closed by flixlix** 2023-06-08 07:46 UTC
Labels: bug

**Comment by tigers75** [comment] 2023-06-17 11:50
Seeing the number of duplicates I think at least one of the issue should not be closed and left on the list marked as bug with the related info. I know it’s in the readme, but it’d be much clearer for everyone finding an open issue.
