### ISSUE TITLE
Visual editor not working

### ISSUE THREAD

**Issue by AJediIAm** [flixlix/power-flow-card-plus#207] opened 2023-05-28 10:02 UTC
I just downloaded version 1.3 of this frontend integration.
When I add a new Power flow card to a dashboard, I get the following screen:
![image](https://github.com/flixlix/power-flow-card-plus/assets/5879533/f3c6fe88-87e3-4797-a33b-3515930f67d5)

I tried to play a bit with the configuration, but the error did not go away so I'm not able to use the visual editor.
I'm running a standard HA Yellow with everything updated to the latest version.

Any suggestion how I can troubleshoot the issue?

**Comment by flixlix** [comment] 2023-05-28 11:18
Duplicate of #166 #160 #158 and more...
Go to #166 to see the solution

**Closed by flixlix** 2023-05-28 11:18 UTC

**Comment by AJediIAm** [comment] 2023-05-28 16:11
Thanks!

How likely is it that it will be fixed in card mod?
Can't this be fixed upstream?

**Comment by flixlix** [comment] 2023-05-28 17:31
To me it seems like the owner of card mod (thomasloven) is not accepting / looking at PRs from other people, because there are quite a few open without any comments in there. I created a PR myself in hopes it would be merged, but I opened it more than a month ago and it hasn't been merged yet.

It can definitely be fixed upstream, we just  the Thomas's approval
