### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by slg60** [flixlix/power-flow-card-plus#615] opened 2024-04-27 22:24 UTC
I'm trying to bring my Dryer and my Washing Machine to one bubble. The Dryer is coming over secondary Info.
It works but when the Power goes to 0 and the Sensor behind the entitiy is offline, the Unit W for Watts goes away.
This only happens on secondary Info, not when the dryer gets configured on the main individual entity.
![image](https://github.com/flixlix/power-flow-card-plus/assets/165797359/d3179a11-6e5f-472f-9487-7fe19f17422d)
By the way, I also see now flow activity for the secondary info, even when there is power consumption.
Configuration looks like this:
- entity: sensor.waschmaschine_leistung
      name: Tr/Wa
      icon: mdi:washing-machine
      display_zero_state: true
      display_zero: true
      calculate_flow_rate: true
      secondary_info:
        entity: sensor.trockner_leistung
        icon: ''
        display_zero: true
        unit_white_space: false
        accept_negative: false
        color_value: false
        template: ''
        display_zero_tolerance: 1
      color_value: false
      show_direction: false
      inverted_animation: false
      use_metadata: false
      color:
        - 137
        - 19
        - 11
      color_icon: true
      display_zero_tolerance: 1

**Comment by flixlix** [comment] 2024-04-28 04:55
Duplicate of #597

**Closed by flixlix** 2024-04-28 04:55 UTC
Labels: bug
