### ISSUE TITLE
[FEATURE REQUEST] customizable tap / click action

### ISSUE THREAD

**Issue by brechtvhb** [flixlix/power-flow-card-plus#660] opened 2024-07-08 13:08 UTC
I would like to be able to set the tap action for each circle.
For each circle i have a page that shows more detail than just the entity. I would be able to navigate to those pages  when tapping the circle.

Eg:

```
  solar:
    icon: fapro:solar-panel
    entity: sensor.solar_total_power_output
    tap_action:
      action: navigate
      navigation_path: /lovelace/solar
```

**Comment by timdreier** [comment] 2024-07-11 14:18
Would also love to see this. Just thought about doing a PR but didn't get the project running for development.

Is it intended to use the devcontainer? For me it just fails to build.

**Comment by timdreier** [comment] 2024-07-11 15:53
Seems to be a duplicate of #610

**Comment by flixlix** [comment] 2024-08-26 09:44
added this feature in v0.2.3 🎉

**Closed by flixlix** 2024-08-26 09:44 UTC
Labels: enhancement
