### ISSUE TITLE
"Object.entries" non è una funzione

### ISSUE THREAD

**Issue by carlogithu** [flixlix/power-flow-card-plus#254] opened 2023-06-04 18:23 UTC
What to do ? Thanks and sorry if I am a beginner.....

**Comment by flixlix** [comment] 2023-06-04 19:08
Known issue.
From the README:

> ⚠️ Version 0.1 introduced the UI Editor. This Editor is currently incompatible with Card Mod. I created a PR to fix this issue, but it hasn't been merged yet. Here is the [PR #277](https://github.com/thomasloven/lovelace-card-mod/pull/277). Since it hasn't been merged yet, I also released a fork with the changes from the PR. Installing this Version of Card Mod you can use this card in conjunction with Card Mod. [Here is my fork](https://github.com/flixlix/lovelace-card-mod)

Duplicate of #251, #207, #219, #166, #160, #158, #133 and probably more...

You would need to either:
- Remove Card Mod
- Remove Card Mod & Install my version to continue using it on other cards
- Use YAML Editor

**Closed by flixlix** 2023-06-04 19:08 UTC
