### ISSUE TITLE
[BUG] I have changed nothing, but the house load is wrong?

### ISSUE THREAD

**Issue by neildsb** [flixlix/power-flow-card-plus#263] opened 2023-06-07 15:35 UTC
I the card has been working flawlessly, however today, I have a strange output as a result of still generating 2kw and exporting on the battery....

![image](https://github.com/flixlix/power-flow-card-plus/assets/91122872/c46c4658-0231-4fc6-8b9f-37e1721c81b6)

![image](https://github.com/flixlix/power-flow-card-plus/assets/91122872/da563fae-1c66-4323-aca9-155017b4e02e)

![image](https://github.com/flixlix/power-flow-card-plus/assets/91122872/734810a7-48c9-43f7-a7b7-6d27757d88b5)

**Comment by flixlix** [comment] 2023-06-07 15:36
Duplicate of #258 
Although I'm very busy atm, I will try to fix it in the next few days

**Closed by flixlix** 2023-06-07 15:36 UTC
Labels: bug
