### ISSUE TITLE
[FEATURE REQUEST] - Additional Individual Items

### ISSUE THREAD

**Issue by mcowger** [flixlix/power-flow-card-plus#344] opened 2023-07-30 22:37 UTC
**Is your feature request related to a problem? Please describe.**
I have multiple high-draw items I'd like to display on the card (2 EVs, 2 AC units, 1 electric dryer), but am limited to 2.

**Describe the solution you'd like**
I'd like support for at least 5 'Individual' Type Items.

**Describe alternatives you've considered**

**Additional context**
<img width="622" alt="Screenshot 2023-07-30 at 3 36 52 PM" src="https://github.com/flixlix/power-flow-card-plus/assets/1929548/9dbc3ae5-c3c9-4871-b008-8a104c0f3dad">

**Comment by flixlix** [comment] 2023-07-31 07:15
This is a duplicate of multiple issues on here and is not currently planned

**Closed by flixlix** 2023-07-31 07:15 UTC
Labels: enhancement

**Comment by mcowger** [comment] 2023-07-31 17:49
Are you open to a PR?

**Comment by flixlix** [comment] 2023-07-31 19:45
Yes of course! We would have to discuss the layout in case the card gets small though...
