### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Buktahula** [flixlix/power-flow-card-plus#251] opened 2023-06-02 08:32 UTC
**Describe the bug**
Cant start the UI Editor

**To Reproduce**

**Expected behavior**
Visual editor is not supported for this configuration:
s.entries is not a function
You can still edit your config in YAML.

**Screenshots**

**Browser Console Errors**
Visual editor is not supported for this configuration:
s.entries is not a function
You can still edit your config in YAML.

**Desktop (please complete the following information):**
 - OS:Windows11
 - Browser Chrome
 - Version 114.0.5735.91
**Smartphone (please complete the following information):**

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment] 2023-06-02 08:54
Known issue.
From the README:

> ⚠️ Version 0.1 introduced the UI Editor. This Editor is currently incompatible with Card Mod. I created a PR to fix this issue, but it hasn't been merged yet. Here is the [PR #277](https://github.com/thomasloven/lovelace-card-mod/pull/277). Since it hasn't been merged yet, I also released a fork with the changes from the PR. Installing this Version of Card Mod you can use this card in conjunction with Card Mod. [Here is my fork](https://github.com/flixlix/lovelace-card-mod)

Duplicate of #207, #219, #166, #160, #158, #133 and probably more...

**Closed by flixlix** 2023-06-02 08:54 UTC
Labels: bug
